- name: connect ssh and launch production version of deploy-client.sh
  hosts: server1
  remote_user: ubuntu

  tasks:
  - name: clear folder before sync
    shell: rm -rf kubernetes-showtime-project/build_front_client_prod/*
  - name: Rsync CI folder to remote prod folder
    synchronize:
      src: /var/www/html/showtime_CLIENT/dist/
      dest: /home/ubuntu/kubernetes-showtime-project/build_front_client_prod/
      recursive: yes
      rsync_opts:
        - "--delete"
        - "--omit-dir-times"
        - "--no-perms"
  - name: launch deploy script for production client front
    shell: cd kubernetes-showtime-project/host_prod && sudo bash deploy-client.sh
    register: result
