name: workflow production
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Deploy prod'
        required: true
        default: 'latest'
jobs:
  sonarqube-test:
    environment: production
    runs-on: ubuntu-latest
    container:
      image: kevinpsirius/pipeline_deployment_image:v10
      env:
        sonar_login: ${{ secrets.SONAR_TOKEN }}
        sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
    steps:
      - name: sonarqubeScan
        run: |
          apt update -y && apt install default-jdk -y
          cd /var/www/html && git clone https://github.com/JAKY99/showtime_CLIENT.git
          git checkout main
          cd /var/www/html/showtime_CLIENT && mv prod.sonar-project.properties sonar-project.properties
          cd /var/www/html/showtime_CLIENT && sed -i "s/SONAR_LOGIN/$sonar_login/g" sonar-project.properties
          cd /var/www/html/showtime_CLIENT && sed -i "s/SONAR_HOST_URL/$(echo $sonar_host_url | sed 's/[\/&]/\\&/g')/g" sonar-project.properties
          cd /var/www/html/showtime_CLIENT && npm  i &&  ng test --code-coverage --watch=false
          cd /var/www/html/showtime_CLIENT && npm run sonar
  prod-deploy:
    needs: sonarqube-test
    environment: production
    runs-on: ubuntu-latest
    container:
      image: kevinpsirius/pipeline_deployment_image:v10
#      options: --cpus 0.20 exemple selenium prod :           selenium-side-runner --base-url https://showtime-app.click/ --server http://18.116.177.62:30015/wd/hub /var/www/html/showtime_CLIENT/ng_e2e_script.side --debug
      env:
        sshKey: ${{ secrets.SSH_KEY }}
    steps:
      - name: Generate new dist for staging
        run: |
          cd /var/www/html && git clone https://github.com/JAKY99/showtime_CLIENT.git
          cd /var/www/html/showtime_CLIENT && node --max-old-space-size=2048 $(which npm) i && ng test --watch=false && node --max-old-space-size=2048 $(which ng) build --configuration production --source-map=false --build-optimizer=false --optimization=false --progress=false --statsJson=false  --aot=true --showCircularDependencies=false --namedChunks=false --outputHashing=none --vendorChunk=false
      - name: Generate SSH connection to server with ansible for staging
        run: |
          touch /var/www/html/mypckey.pem &&  chmod 600 /var/www/html/mypckey.pem && echo "$sshKey" >> /var/www/html/mypckey.pem
          cd /var/www/html/showtime_CLIENT/playbook && ansible-playbook deploy-prod-client-front.yml -e "ansible_ssh_timeout=180"
          curl https://showtime-app.click/api/api/v1/version/set?type=client
