name: workflow autoupdate staging
on:
  push:
    branches:
      - develop
jobs:
  sonarqube-test:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=showtime_CLIENT_dev
            -Dsonar.verbose=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  staging-deploy:
    needs: sonarqube-test
    environment: staging
    runs-on: ubuntu-latest
    container:
      image: kevinpsirius/pipeline_deployment_image:v10
#      options: --cpus 0.45        ex selenium cmd dev:  selenium-side-runner --base-url https://dev.showtime-app.click/ --server http://18.116.177.62:30015/wd/hub /var/www/html/showtime_CLIENT/ng_e2e_script.side --debug
      env:
        sshKey: ${{ secrets.SSH_KEY }}
    steps:
      - name: Generate new dist for staging
        run: |
          cd /var/www/html && git clone https://github.com/JAKY99/showtime_CLIENT.git
          cd /var/www/html/showtime_CLIENT && node --max-old-space-size=2048 $(which npm) i && ng test --watch=false && node --max-old-space-size=2048 $(which ng) build --configuration staging --source-map=false --build-optimizer=false --optimization=false --progress=false --statsJson=false  --aot=true --showCircularDependencies=false --namedChunks=false --outputHashing=none --vendorChunk=false


      - name: Generate SSH connection to server with ansible for staging
        run: |
          touch /var/www/html/mypckey.pem &&  chmod 600 /var/www/html/mypckey.pem && echo "$sshKey" >> /var/www/html/mypckey.pem
          cd /var/www/html/showtime_CLIENT/playbook && ansible-playbook deploy-dev-client-front.yml -e "ansible_ssh_timeout=180"
          curl https://dev.showtime-app.click/api/api/v1/version/set?type=client
